"""feat: add sender_name to mpesa_transactions

Revision ID: 1ee4ecb2d98b
Revises: c281e4b2da8e
Create Date: 2026-06-28 20:02:22.621706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee4ecb2d98b'
down_revision: Union[str, None] = 'c281e4b2da8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('sender_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa_transactions', 'sender_name')
    # ### end Alembic commands ###
