"""fix: expand mpesa_transactions phone column to 64 chars

Revision ID: c281e4b2da8e
Revises: fea65eb9697a
Create Date: 2026-06-28 19:38:00.280682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c281e4b2da8e'
down_revision: Union[str, None] = 'fea65eb9697a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesa_transactions', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesa_transactions', 'phone',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
