"""add balance_after to installments

Revision ID: c49b34ead60e
Revises: 20260627_add_defaulter_tracking
Create Date: 2026-06-28 16:08:16.977826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c49b34ead60e'
down_revision: Union[str, None] = '20260627_add_defaulter_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('customers', 'profile_image_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.add_column('installments', sa.Column('balance_after', sa.Float(), nullable=True))
    op.alter_column('loans', 'arrears_since',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('mpesa_transactions', 'loan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('mpesa_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_mpesa_transactions_id'), 'mpesa_transactions', ['id'], unique=False)
    op.drop_index('uq_users_email', table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.create_index('uq_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_mpesa_transactions_id'), table_name='mpesa_transactions')
    op.alter_column('mpesa_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('mpesa_transactions', 'loan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'arrears_since',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('installments', 'balance_after')
    op.alter_column('customers', 'profile_image_url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('customers', 'phone_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
