"""make_mpesa_loan_id_nullable

Revision ID: fea65eb9697a
Revises: c49b34ead60e
Create Date: 2026-06-28 17:20:50.381153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fea65eb9697a'
down_revision: Union[str, None] = 'c49b34ead60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesa_transactions', 'loan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesa_transactions', 'loan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
